application: GocoreWebproxy
version: first
module: default
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_concurrent_requests: 40

handlers:
- url: /static
  static_dir: static
  secure: optional

- url: /_ah/warmup
  script: mirror.app
  secure: optional

- url: /.*
  script: mirror.app
  secure: optional
